
spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: test
    listener:
      simple:
        acknowledge-mode: manual  # 配置自动adk


server:
  port: 8091